name: 'Terraform'

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        # Pin version, 1.6.0+ breaks for some reason
        terraform_version: "1.5.7"

    # Get backend.conf
    - name: Backend Configuration
      run: |
        echo ${BACKEND_CONF} | base64 -d > .backend.conf
        echo ${SECRETS_TFVARS} | base64 -d > .secrets.tfvars
      env:
        BACKEND_CONF: ${{ secrets.BACKEND_CONF }}
        SECRETS_TFVARS: ${{ secrets.SECRETS_TFVARS }}

    - name: Terraform Init
      run: terraform init -backend-config=.backend.conf

    - name: Terraform Format
      run: terraform fmt -check -diff -recursive

    - name: Terraform Plan
      run: terraform plan -input=false -parallelism=1 -var-file=.secrets.tfvars

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false -parallelism=1 -var-file=.secrets.tfvars
